In [2]:
import pandas as pd
import numpy as np

from pytrends.request import TrendReq
from pytrends.exceptions import ResponseError

import time

In [4]:
data = pd.read_csv('./Data/clusters.csv')
data

             word     tfidf  label
0          punish  0.547101      0
1           cover  0.564675      0
2          global  0.709860      0
3           arena  0.614520      0
4         highest  0.577350      0
...           ...       ...    ...
1682   invitation  0.512852      9
1683      compare  0.752250      9
1684         band  0.742651      9
1685      wedding  0.611157      9
1686  complicated  0.464108      9

[1687 rows x 3 columns]

In [5]:
def infer_topic(data):
    topics_data = pd.DataFrame()
    for kw in data['word']:
        while True:
            try:
                trends.build_payload(kw_list=[kw])
                break
            except ResponseError as e:
                print('Retrying:', e)
                time.sleep(10)
            except Error as e:
                print('Bad situation...')
                time.sleep(10)

        related_topics = trends.related_topics()[kw]['top'][['topic_title', 'topic_type']][:3].T
        
        tmp = pd.DataFrame(pd.concat([related_topics.loc['topic_title', :], related_topics.loc['topic_type', :]])).T
        tmp.columns = [f'topic_title_{c}' for c in tmp.columns[:3]] + [f'topic_type_{c}' for c in tmp.columns[3:]]

        topics_data = pd.concat([topics_data, tmp], axis=0)
        
        time.sleep(1)
    return topics_data

In [ ]:
topics = infer_topic(viz_data)
topics